name: Code formatter and linter

on:
  push:
    branches:
      - master
      - dev
      - main
  pull_request:
    branches:
      - master
      - dev
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          pip install poetry
          poetry install
      - name: Format with isort and black
        run: |
          poetry run isort ./
          poetry run black ./
      - name: Linting with ruff
        run: |
          poetry run ruff ./
      - name: Typecheck with pyright
        run: |
          poetry run pyright ./
